### ISSUE TITLE
BE: Weekly report template

### ISSUE THREAD

**Issue by f3rland** [hatchways/team-bulldozer-1#17]
![email.png](https://images.zenhubusercontent.com/5f2d339993085014f6d505cc/5466a086-f64a-4cd4-bb0e-707b07b44d20)

**Comment by splantebulldozer** [comment]
Here's a starting point, I couldn't find your branch to integrate it w/ the sending logic so I put it in a gist, lmk it I can help!

mjml: https://gist.github.com/splantebulldozer/ec3e2a081965b70eaeecadec1b94f446
html: https://gist.github.com/splantebulldozer/8541f1f9eebe80beecd9a9b990f558d6
