### ISSUE TITLE
BE: Run reports on a weekly basis

### ISSUE THREAD

**Issue by f3rland** [hatchways/team-bulldozer-1#18]
Will use queue provided by [OptimalBits/bull](https://github.com/OptimalBits/bull) library

**Comment by skassam21** [comment]
sendgrid templates - https://sendgrid.com/solutions/email-api/dynamic-email-templates/

**Comment by f3rland** [comment]
Note to self:

- https://sendgrid.com/docs/ui/sending-email/how-to-send-an-email-with-dynamic-transactional-templates/
- https://sendgrid.com/docs/ui/account-and-settings/api-keys/#creating-an-api-key
- https://sendgrid.com/docs/for-developers/sending-email/using-handlebars/
