### ISSUE TITLE
FS: Socket setup

### ISSUE THREAD

**Issue by skassam21** [hatchways/team-bulldozer-1#35]
- [x] use this package socket.io for real-time notifications
- [x] Setup socket server on the backend
- [x] Setup client connection (should connect if the user is authed - see code below)
- [x] We also want an object to keep track of which users are currently connected - using a service, a database like Redis, or we can for now just use an in-memory variable (not recommended for the future, but it works for this project)
```
io.on('connect', (socket)=>{
socket.headers.cookies[''] // can do some validation here
socket.disconnect()
})
```

**Comment by f3rland** [comment]
@skassam21 
> We also want an object to keep track of which users are currently connected

We currently only have email & company name. So we go with Company Name I guess?
Also, what will we do with that list of connected users? Eventually display names or count?
